# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'BoxOffice' do
  use_frameworks!
  pod 'SDWebImage'

  target 'BoxOfficeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BoxOfficeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
